const app = document.getElementById("app");
const progressText = document.getElementById("progressText");
const scoreText = document.getElementById("scoreText");
const progressBar = document.getElementById("progressBar");

const TASKS = MODULE_2024_TASKS;
const TOTAL_POINTS = 12;
const state = { screen:"intro", index:0, answers:Array(TASKS.length).fill(null), midpointShown:false, reviewIndex:0, practiceTopic:null, practiceTasks:[], practiceIndex:0, practiceAnswers:[], practiceScore:0, completedPractice:{} };
const labels = { first:"Az első alak helyes", second:"A második alak helyes", both:"Mindkettő helyes", neither:"Egyik sem helyes" };
const symbols = { first:"1", second:"2", both:"X", neither:"0" };

function sameSelection(a,b){
  if(!Array.isArray(a)||!Array.isArray(b)) return false;
  return a.length===b.length && [...a].sort().every((v,i)=>v===[...b].sort()[i]);
}
function isCorrect(task, answer){
  if(answer===null||answer===undefined) return false;
  return task.type==="multi-select-pair" ? sameSelection(answer,task.correct) : task.correct===answer;
}
function answeredCount(){ return state.answers.filter(a=>a!==null).length; }
function score(){ return TASKS.reduce((sum,t,i)=>sum+(isCorrect(t,state.answers[i])?1:0),0); }
function updateStatus(){ const n=answeredCount(); progressText.textContent=`${n} / ${TASKS.length}`; scoreText.textContent=`${score()} / ${n}`; document.getElementById("totalText").textContent=TOTAL_POINTS; progressBar.style.width=`${n/TASKS.length*100}%`; }

function renderIntro(){
  state.screen="intro"; updateStatus();
  app.innerHTML=`<section class="hero"><div class="hero-inner"><a class="module-return" href="index.html">← Évválasztó</a><span class="badge">✦ 2024. januári feladatok</span><h2>Helyesírási kihívás</h2><p class="source-note">Két hatfeladatos helyesírási blokk</p><p class="lead">Először 1–2–X–0 feladatok várnak rád. A második részben jelöld ki az összes helyesen írt alakot! Minden feladat 1 pontot ér.</p><button class="primary" id="startBtn">Kezdhetjük</button></div></section>`;
  document.getElementById("startBtn").onclick=renderQuestion;
}
function renderChoice(task,selected){ return `<h2>Melyik alak helyes?</h2><div class="word-pair"><div class="word"><span>${task.first}</span></div><div class="word"><span>${task.second}</span></div></div><div class="answers">${Object.entries(labels).map(([v,l])=>`<button class="answer ${selected===v?"selected":""}" data-answer="${v}"><span class="answer-symbol">${symbols[v]}</span>${l}</button>`).join("")}</div>`; }
function renderMulti(task,selected){
  const submitted=Array.isArray(selected); const chosen=submitted?selected:[];
  return `<h2>Jelöld ki a helyesen írt alakot vagy alakokat!</h2><p class="fill-instruction">Egy vagy mindkét alak helyes lehet.</p><div class="multi-pair" id="multiPair"><button class="word multi-choice ${chosen.includes("first")?"selected":""}" data-choice="first" ${submitted?"disabled":""}>${task.first}</button><button class="word multi-choice ${chosen.includes("second")?"selected":""}" data-choice="second" ${submitted?"disabled":""}>${task.second}</button></div>${submitted?"":`<div class="fill-submit-row"><button class="primary" id="submitMultiBtn" disabled>Válasz beküldése</button></div>`}`;
}
function renderQuestion(){
  state.screen="question"; const task=TASKS[state.index], selected=state.answers[state.index], submitted=selected!==null; updateStatus();
  app.innerHTML=`<section class="question"><div class="question-head"><span>${state.index+1}. feladat</span><span>1 pont</span></div><p class="task-source">${task.source}</p>${task.type==="multi-select-pair"?renderMulti(task,selected):renderChoice(task,selected)}<div class="navigation"><button class="nav-btn" id="backBtn" ${state.index===0?"disabled":""}>← Vissza</button><button class="nav-btn next" id="nextBtn" ${submitted?"":"disabled"}>${state.index===TASKS.length-1?"Befejezem":"Következő →"}</button></div></section>`;
  if(task.type==="multi-select-pair" && !submitted){
    const draft=new Set(); const submit=document.getElementById("submitMultiBtn");
    app.querySelectorAll(".multi-choice").forEach(btn=>btn.onclick=()=>{ const v=btn.dataset.choice; draft.has(v)?draft.delete(v):draft.add(v); btn.classList.toggle("selected",draft.has(v)); submit.disabled=draft.size===0; });
    submit.onclick=()=>{ if(!draft.size)return; state.answers[state.index]=[...draft]; SCORM.setProgress(score(),TOTAL_POINTS); renderQuestion(); };
  } else if(task.type!=="multi-select-pair"){
    app.querySelectorAll(".answer").forEach(btn=>btn.onclick=()=>{ state.answers[state.index]=btn.dataset.answer; SCORM.setProgress(score(),TOTAL_POINTS); renderQuestion(); });
  }
  document.getElementById("backBtn").onclick=()=>{ if(state.index>0){state.index--;renderQuestion();} };
  document.getElementById("nextBtn").onclick=()=>{ if(state.answers[state.index]===null)return; if(state.index===TASKS.length-1){renderResult();return;} if(state.index===5&&!state.midpointShown){state.midpointShown=true;renderMidpoint();return;} state.index++;renderQuestion(); };
}
function renderMidpoint(){ updateStatus(); app.innerHTML=`<section class="midpoint"><div class="hero-inner"><span class="badge">Az első blokk kész</span><h2>Most több helyes alak is lehet.</h2><p class="lead">Az első hat feladatból ${score()} pontot szereztél. A következő sorokban egy vagy mindkét alakot jelöld ki, majd küldd be a választ!</p><button class="primary" id="continueBtn">Jöhet a következő hat</button></div></section>`; document.getElementById("continueBtn").onclick=()=>{state.index=6;renderQuestion();}; }

function practiceTopicForTask(task){ const t=task.tags||[]; if(t.includes("számnevek írása"))return "számnevek írása"; if(t.includes("mássalhangzók és toldalékolás"))return "mássalhangzók és toldalékolás"; if(t.includes("felszólító mód"))return "felszólító mód"; if(t.includes("igekötők"))return "igekötők"; if(t.includes("egybe- és különírás"))return "egybe- és különírás"; if(t.includes("j és ly"))return "j és ly"; if(t.includes("kis- és nagybetű")||t.includes("földrajzi név"))return "kis- és nagybetű"; if(t.includes("jelentés"))return "jelentés"; return null; }
function getRecommendedTopics(){ const c={}; TASKS.forEach((t,i)=>{if(!isCorrect(t,state.answers[i])){const p=practiceTopicForTask(t);if(p&&PRACTICE_TOPICS[p])c[p]=(c[p]||0)+1;}}); return Object.entries(c).sort((a,b)=>b[1]-a[1]).map(x=>x[0]); }
function allPracticeTopics(){return Object.keys(PRACTICE_TOPICS);} function topicTitle(t){return PRACTICE_TOPICS[t]?.title||t;}
function resultTitle(p){if(p===12)return"Hibátlan munka!";if(p>=9)return"Nagyon szép eredmény!";if(p>=6)return"Jó alapokra építhetsz.";return"Most már tudjuk, mit érdemes gyakorolni.";}
function renderResult(){ state.screen="result";updateStatus();const total=score(),rec=getRecommendedTopics();SCORM.setResult(total,TOTAL_POINTS);app.innerHTML=`<section class="result"><span class="badge">Kész a 2024-es feladatsor</span><h2>${resultTitle(total)}</h2><div class="result-score"><div><strong>${total}/12</strong><span>pont</span></div></div>${rec.length?`<div class="focus-block"><p>Érdemes még gyakorolnod:</p><div class="tag-list">${rec.map(t=>`<span class="topic-tag">${topicTitle(t)}</span>`).join("")}</div></div>`:""}<div class="practice-offer"><span class="practice-icon">✦</span><div><h3>Személyre szabott gyakorlás</h3><p>A hibáid alapján a közös gyakorlóbankból kapsz ajánlott témákat.</p></div></div><div class="result-actions"><button class="primary" id="practiceBtn">Gyakorló témák megnyitása</button><button class="secondary" id="reviewBtn">Válaszaim áttekintése</button><button class="secondary" id="restartBtn">Újrakezdem</button><a class="secondary module-back-link" href="index.html">Másik év választása</a></div></section>`;document.getElementById("practiceBtn").onclick=renderPracticeHub;document.getElementById("reviewBtn").onclick=()=>{state.reviewIndex=firstWrongIndex();renderReview();};document.getElementById("restartBtn").onclick=restart; }
function renderPracticeHub(){state.screen="practice-hub";const rec=getRecommendedTopics(),topics=rec.length?rec:allPracticeTopics();app.innerHTML=`<section class="practice-hub"><div class="review-toolbar"><button class="nav-btn" id="backToResult">← Eredmény</button><span>${rec.length?"Személyre szabott útvonal":"Teljes gyakorlóbank"}</span></div><div class="practice-hub-head"><span class="badge">${topics.length} ${rec.length?"ajánlott":"választható"} terület</span><h2>Mit gyakoroljunk?</h2></div><div class="practice-topic-grid">${topics.map((t,i)=>{const d=PRACTICE_TOPICS[t],done=state.completedPractice[t];return`<button class="practice-topic-card ${done?"completed":""}" data-topic="${t}"><span class="topic-order">${done?"✓":i+1}</span><span class="topic-card-copy"><strong>${d.title}</strong><small>${d.description}</small></span><span class="topic-card-score">${done?`${done.score}/${done.total}`:"5 feladat"}</span></button>`;}).join("")}</div>${rec.length?`<details class="all-topics"><summary>Más témát is gyakorolnék</summary><div class="tag-list topic-shortcuts">${allPracticeTopics().filter(t=>!topics.includes(t)).map(t=>`<button class="topic-tag topic-shortcut" data-topic="${t}">${topicTitle(t)}</button>`).join("")}</div></details>`:""}</section>`;document.getElementById("backToResult").onclick=renderResult;app.querySelectorAll("[data-topic]").forEach(b=>b.onclick=()=>startPractice(b.dataset.topic));}
function startPractice(t){state.practiceTopic=t;state.practiceTasks=PRACTICE_TASKS.filter(x=>x.topic===t);state.practiceIndex=0;state.practiceAnswers=Array(state.practiceTasks.length).fill(null);state.practiceScore=0;renderPractice();}
function renderPractice(){state.screen="practice";const task=state.practiceTasks[state.practiceIndex],answer=state.practiceAnswers[state.practiceIndex],answered=answer!==null,correct=answered&&answer===task.correct;app.innerHTML=`<section class="practice-screen"><div class="question-head"><span>${topicTitle(task.topic)}</span><span>${state.practiceIndex+1} / ${state.practiceTasks.length}</span></div><span class="topic-tag practice-topic">${topicTitle(task.topic)}</span><h2>${task.prompt}</h2><div class="practice-options">${task.options.map((o,i)=>`<button class="practice-option ${answered?(i===task.correct?"correct":i===answer?"wrong":""):""}" data-index="${i}" ${answered?"disabled":""}>${o}</button>`).join("")}</div>${answered?`<div class="practice-feedback ${correct?"correct":"wrong"}"><span class="practice-feedback-icon"></span><div><strong>${correct?"Helyes döntés":"Ezt most nézzük meg"}</strong><p>${task.explanation}</p></div></div>`:""}<div class="navigation"><button class="nav-btn" id="quitPractice">← Témák</button><button class="nav-btn next" id="nextPractice" ${answered?"":"disabled"}>${state.practiceIndex===state.practiceTasks.length-1?"Gyakorlás befejezése":"Következő →"}</button></div></section>`;app.querySelectorAll(".practice-option").forEach(b=>b.onclick=()=>{const s=Number(b.dataset.index);state.practiceAnswers[state.practiceIndex]=s;if(s===task.correct)state.practiceScore++;renderPractice();});document.getElementById("quitPractice").onclick=renderPracticeHub;document.getElementById("nextPractice").onclick=()=>{if(!answered)return;if(state.practiceIndex===state.practiceTasks.length-1)renderPracticeResult();else{state.practiceIndex++;renderPractice();}};}
function renderPracticeResult(){state.completedPractice[state.practiceTopic]={score:state.practiceScore,total:state.practiceTasks.length};const remaining=getRecommendedTopics().filter(t=>!state.completedPractice[t]);app.innerHTML=`<section class="result practice-result"><span class="badge">${topicTitle(state.practiceTopic)} – kész</span><h2>${state.practiceScore===state.practiceTasks.length?"Nagyon biztosan ment!":"Máris erősebb lett a tudásod."}</h2><div class="result-score small"><div><strong>${state.practiceScore}/${state.practiceTasks.length}</strong><span>gyakorlópont</span></div></div><p class="lead">A felvételi eredményed továbbra is <strong>${score()}/12</strong>.</p><div class="result-actions">${remaining.length?`<button class="primary" id="nextTopic">Következő ajánlott téma</button>`:""}<button class="secondary" id="backTopics">Vissza a témákhoz</button><button class="secondary" id="againPractice">Ezt újra gyakorlom</button></div></section>`;if(remaining.length)document.getElementById("nextTopic").onclick=()=>startPractice(remaining[0]);document.getElementById("backTopics").onclick=renderPracticeHub;document.getElementById("againPractice").onclick=()=>startPractice(state.practiceTopic);}
function answerText(task,a){if(task.type==="multi-select-pair"){if(!Array.isArray(a))return"Nincs válasz";return a.map(v=>v==="first"?task.first:task.second).join(" + ");}return `${symbols[a]||"—"} – ${labels[a]||"Nincs válasz"}`;}
function renderReview(){const task=TASKS[state.reviewIndex],a=state.answers[state.reviewIndex],ok=isCorrect(task,a);app.innerHTML=`<section class="review-screen"><div class="review-toolbar"><button class="nav-btn" id="resultBtn">← Eredmény</button><span>${state.reviewIndex+1} / 12</span></div><p class="task-source">${task.source}</p><div class="review-status ${ok?"correct":"wrong"}"><span class="status-icon"></span><div><strong>${ok?"Helyes döntés":"Ezt most érdemes átnézni"}</strong><span>${ok?"1 pont":"0 pont"}</span></div></div><div class="review-words"><div class="review-word"><small>Első alak</small><strong>${task.first}</strong></div><div class="review-word"><small>Második alak</small><strong>${task.second}</strong></div></div><div class="answer-comparison"><div><small>A te válaszod</small><strong>${answerText(task,a)}</strong></div><div class="correct-answer-box"><small>Helyes megoldás</small><strong>${answerText(task,task.correct)}</strong></div></div><div class="short-explanation"><h3>Röviden</h3><p>${task.explanation}</p></div><div class="review-navigation"><button class="nav-btn" id="prevReviewBtn" ${state.reviewIndex===0?"disabled":""}>← Előző</button><div class="review-dots">${TASKS.map((t,i)=>`<button class="review-dot ${i===state.reviewIndex?"active":""} ${isCorrect(t,state.answers[i])?"correct":"wrong"}" data-index="${i}"></button>`).join("")}</div><button class="nav-btn next" id="nextReviewBtn">${state.reviewIndex===11?"Vissza az eredményhez":"Következő →"}</button></div></section>`;document.getElementById("resultBtn").onclick=renderResult;document.getElementById("prevReviewBtn").onclick=()=>{if(state.reviewIndex>0){state.reviewIndex--;renderReview();}};document.getElementById("nextReviewBtn").onclick=()=>{if(state.reviewIndex===11)renderResult();else{state.reviewIndex++;renderReview();}};app.querySelectorAll(".review-dot").forEach(d=>d.onclick=()=>{state.reviewIndex=Number(d.dataset.index);renderReview();});}
function firstWrongIndex(){const i=TASKS.findIndex((t,n)=>!isCorrect(t,state.answers[n]));return i<0?0:i;}
function restart(){state.index=0;state.answers=Array(12).fill(null);state.midpointShown=false;state.reviewIndex=0;state.completedPractice={};renderIntro();}
SCORM.init();renderIntro();
