const MODULE_2024_TASKS = [
  { id:"2024-a1", group:"toto", type:"choice-pair", source:"2024. január • 1. blokk • a)", first:"tesztel", second:"teszttel", correct:"both", points:1, tags:["mássalhangzók és toldalékolás"], explanation:"Mindkettő helyes. A tesztel ige, a teszttel pedig a teszt főnév -val/-vel ragos alakja: teszt + vel → teszttel." },
  { id:"2024-a2", group:"toto", type:"choice-pair", source:"2024. január • 1. blokk • b)", first:"Margit Híd", second:"Margit-híd", correct:"neither", points:1, tags:["kis- és nagybetű","földrajzi név"], explanation:"A budapesti híd neve: Margit híd. Ezért a két megadott alak közül egyik sem helyes." },
  { id:"2024-a3", group:"toto", type:"choice-pair", source:"2024. január • 1. blokk • c)", first:"lefolyt", second:"lefojt", correct:"both", points:1, tags:["jelentés"], explanation:"Mindkettő helyes, de mást jelent: a lefolyt a folyik igéhez, a lefojt a fojt igéhez kapcsolódik." },
  { id:"2024-a4", group:"toto", type:"choice-pair", source:"2024. január • 1. blokk • d)", first:"hozzd", second:"hozd", correct:"second", points:1, tags:["felszólító mód"], explanation:"A hoz ige felszólító módú, határozott ragozású alakja: hozd." },
  { id:"2024-a5", group:"toto", type:"choice-pair", source:"2024. január • 1. blokk • e)", first:"papírzsebkendő", second:"papír zsebkendő", correct:"second", points:1, tags:["egybe- és különírás"], explanation:"A papír anyagot jelölő szó, a zsebkendő pedig már összetett szó, ezért: papír zsebkendő." },
  { id:"2024-a6", group:"toto", type:"choice-pair", source:"2024. január • 1. blokk • f)", first:"meg akarta fogni", second:"megakarta fogni", correct:"first", points:1, tags:["igekötők"], explanation:"Az akarta szó az igekötő és az ige közé ékelődik, ezért különírjuk: meg akarta fogni." },

  { id:"2024-b1", group:"multi", type:"multi-select-pair", source:"2024. január • 2. blokk • a)", first:"forgószínpad", second:"kacsalábon forgó palota", correct:["first","second"], points:1, tags:["egybe- és különírás"], explanation:"Mindkettő helyes. A forgószínpad összetett szó, a kacsalábon forgó palota szókapcsolat." },
  { id:"2024-b2", group:"multi", type:"multi-select-pair", source:"2024. január • 2. blokk • b)", first:"hagyjátok", second:"higyjétek", correct:["first"], points:1, tags:["felszólító mód"], explanation:"A hagyjátok helyes. A hisz ige megfelelő felszólító módú alakja: higgyétek." },
  { id:"2024-b3", group:"multi", type:"multi-select-pair", source:"2024. január • 2. blokk • c)", first:"be fogja írni", second:"befogja a fülét", correct:["first","second"], points:1, tags:["igekötők"], explanation:"Mindkettő helyes. A be fogja írni szerkezetben a fogja közbeékelődik; a befogja alakban az igekötő közvetlenül az ige előtt áll." },
  { id:"2024-b4", group:"multi", type:"multi-select-pair", source:"2024. január • 2. blokk • d)", first:"ezerkilencszázötvennyolc", second:"ötmillióhat", correct:["first"], points:1, tags:["számnevek írása"], explanation:"Az ezerkilencszázötvennyolc helyes. Az ötmillióhat alak helyesen kötőjeles: ötmillió-hat." },
  { id:"2024-b5", group:"multi", type:"multi-select-pair", source:"2024. január • 2. blokk • e)", first:"papagáj", second:"sirály", correct:["first","second"], points:1, tags:["j és ly"], explanation:"Mindkét szó helyesen van írva: papagáj, sirály." },
  { id:"2024-b6", group:"multi", type:"multi-select-pair", source:"2024. január • 2. blokk • f)", first:"beljebb", second:"kijjebb", correct:["first","second"], points:1, tags:["mássalhangzók és toldalékolás"], explanation:"Mindkét alak helyes: beljebb és kijjebb." }
];
